# Getting Started with Algorithmic Trading 

In this activity, students will write a trading algorithm that uses Python to represent the conditions of a simple trading strategy.

## Instructions:

1. Using the data that the starter notebook supplies, run the code cells that import the required libraries.

2. Visualize the price movement of the DataFrame by using the `hvplot` function.

3. Create a new variable called 'daily_returns' and 'daily_returns_lagged' and determine the correlation between the variables 'daily_returns' and 'daily_returns_lagged'.

4. Based on the correlation, create a trading strategy based on the previous day's returns.

4. Add a column named “trade_type” to the DataFrame that shows whether you have a 'long' or 'short' position on that day.

## Step 1: Using the data that the starter notebook supplies, run the code cells that import the required libraries, and then create a Pandas DataFrame named `amd_df`.

In [4]:
# Import required libraries
import pandas as pd
import numpy as np
from pathlib import Path
import hvplot.pandas

In [5]:
# Read the fntk.csv file from the Resources folder into a Pandas DataFrame
# Set the `Date` column as the DateTimeIndex
fntk_df = pd.read_csv(
    Path("../Resources/fntk3.csv"), 
    index_col="Date",
    parse_dates=True, 
    infer_datetime_format=True
)

# Review the DataFrame
fntk_df.head()

                              Close
Date
2019-01-02 05:00:00+00:00  135.4100
2019-01-03 05:00:00+00:00  131.8902
2019-01-04 05:00:00+00:00  137.9400
2019-01-07 05:00:00+00:00  138.2300
2019-01-08 05:00:00+00:00  142.5843

In [6]:
# Create a DataFrame filtering only the index and Close columns
fntk_df = fntk_df.loc[:,["Close"]]

# Review the DataFrame
fntk_df.head()

                              Close
Date
2019-01-02 05:00:00+00:00  135.4100
2019-01-03 05:00:00+00:00  131.8902
2019-01-04 05:00:00+00:00  137.9400
2019-01-07 05:00:00+00:00  138.2300
2019-01-08 05:00:00+00:00  142.5843

In [7]:
# Use hvplot to visualize the DataFrame
fntk_df.hvplot()

:Curve   [Date]   (Close)

In [8]:
# Use hvplot to visualize the DataFrame
fntk_df['daily_returns'] = fntk_df['Close'].pct_change()
fntk_df['daily_returns_lagged'] = fntk_df['daily_returns'].shift(1)
fntk_df.head()

                              Close  daily_returns  daily_returns_lagged
Date
2019-01-02 05:00:00+00:00  135.4100            NaN                   NaN
2019-01-03 05:00:00+00:00  131.8902      -0.025994                   NaN
2019-01-04 05:00:00+00:00  137.9400       0.045870             -0.025994
2019-01-07 05:00:00+00:00  138.2300       0.002102              0.045870
2019-01-08 05:00:00+00:00  142.5843       0.031500              0.002102

In [9]:
# Create a table that shows the correlation between 'daily_returns' and 'daily_returns_lagged'
fntk_df[['daily_returns','daily_returns_lagged']].corr().style.background_gradient()

In [10]:
# Create a trading signal based on the lagged returns
fntk_df['trade_type'] =np.where(fntk_df['daily_returns_lagged']<0,1,-1)

In [11]:
# Review the DataFrame
fntk_df.head(10)

,Close,daily_returns,daily_returns_lagged,trade_type
Date,,,,
2019-01-02 05:00:00+00:00,135.4100,NaN,NaN,-1
2019-01-03 05:00:00+00:00,131.8902,-0.025994,NaN,-1
2019-01-04 05:00:00+00:00,137.9400,0.045870,-0.025994,1
2019-01-07 05:00:00+00:00,138.2300,0.002102,0.045870,-1
2019-01-08 05:00:00+00:00,142.5843,0.031500,0.002102,-1
2019-01-09 05:00:00+00:00,144.2500,0.011682,0.031500,-1
2019-01-10 05:00:00+00:00,144.1500,-0.000693,0.011682,-1
2019-01-11 05:00:00+00:00,143.7205,-0.002980,-0.000693,1
2019-01-14 05:00:00+00:00,145.6300,0.013286,-0.002980,1
2019-01-15 05:00:00+00:00,148.8200,0.021905,0.013286,-1